spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=RoleBasedHikariPool

spring.datasource.url=jdbc:postgresql://localhost:5432/rolebasedsystem
spring.datasource.username=postgres
spring.datasource.password=postgres

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s
# Use local in-memory cache for local development when Redis is not running
spring.cache.type=simple
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false
logging.level.com.vasyerp.rolebasedsystem.service.CountryServiceImpl=DEBUG
